### ISSUE TITLE
Github SSH connection cmder Windows 10 PC

### ISSUE THREAD

**Issue by NEOMorpheus33** [susanBuck/e15-spring21#7] opened 2021-02-15 03:00 UTC
**Environment**

Github SSH connection cmder Windows 10 PC

**What operating system are you using?**

Windows 10 PC

**The problem is that the .ssh connection won't work**

C:\Users\Joseph\.ssh
λ :\Users\Joseph\.ssh λ ssh -T git@github.com Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts. git@github.com: Permission denied (publickey).C:\Users\Joseph\.ssh λ :\Users\Joseph\.ssh λ ssh -T git@github.com Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts. git@github.com: Permission denied (publickey).. 

**Steps taken**
I followed the video for Windows 10 users on Youtube. I seem to have deleted "all" file permissions though when prompted to hit ok. 

**Additional context**
Is there a way to add back the permissions? Maybe I should delete the config file and try again. There were to options given after I went to advanced tab and hit ok for files that weren't shown in the youtube video.

**Comment by susanBuck** [comment] 2021-02-15 04:31
Hi @NEOMorpheus33 -

Can you run the following command and share the output with us to debug why the SSH connection may be failing?

```bash
$ ssh -vT git@github.com
```

(ref: https://hesweb.dev/e15/notes/git/github#get-more-details-about-a-failed-connection)

You can also bypass the SSH config file (if it's the source of the problem) by explicitly setting the name of the SSH key you wish to connect with.

For example:
```bash
$ ssh -T -i %homepath%/.ssh/hes git@github.com
```

The above command will test your SSH connection with github.com, using the key named *hes*.


**If that works,** we know the problem is related to the SSH config file and we can look closer at the permissions.

**If that does not work,** we know it's a problem with your SSH keys you set up and we can take a closer look at that.

(ref: https://hesweb.dev/e15/notes/git/github#narrow-down-the-source-of-the-problem)

**Comment by NEOMorpheus33** [comment] 2021-02-16 14:02
hmm looks like the hes private key is missing. I'll make one. 

```bash
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: C:\\Users\\Joseph/.ssh/id_rsa
debug1: Trying private key: C:\\Users\\Joseph/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\Joseph/.ssh/id_ecdsa
debug1: Trying private key: C:\\Users\\Joseph/.ssh/id_ed25519
debug1: Trying private key: C:\\Users\\Joseph/.ssh/id_xmss
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).

C:\Users\Joseph>nano hes
'nano' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Joseph>create hes
'create' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Joseph>mk hes
'mk' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Joseph>
```

**Comment by karnaout** [comment] 2021-02-16 14:21
I would've loved to help @NEOMorpheus33 but I unfortunately don't have a PC and don't have access :(

**Comment by susanBuck** [comment] 2021-02-16 15:19
@NEOMorpheus33 Thanks for sharing the output of that command.

For reference, here are the instructions on how to create the *hes* key pair: https://hesweb.dev/e15/notes/git/github#generate-ssh-keys-on-your-computer

After following those steps, to confirm the *hes* public key is successfully created, you can try and output its contents with this command: 

```bash
$ cat %homepath%/.ssh/hes.pub
```

You can also confirm the presence of the private key:

```bash
$ cat %homepath%/.ssh/hes
```

Once you confirm both those keys exist, you want to confirm that your SSH config file contains the line telling SSH to use those keys. Those steps are described here: https://hesweb.dev/e15/notes/git/github#ssh-config-file

Alternatively, you can override the SSH config file and force SSh to connect with the hes key:

```bash
$ ssh -T -i %homepath%/.ssh/hes git@github.com
```

Don't hesitate to let me know if you have follow-up questions as you go through this process.

**Comment by britney-sandau** [comment] 2021-02-17 08:05
@NEOMorpheus33 I hope you got it working. I also had the same error but mine occurred due to clicking on the generic "Ubuntu" server, rather than searching for the "LAMP on Ubuntu 20.04" server on the Marketplace tab during my droplet set up.

I have included some screenshots to show you my mistake in case that helps.

![ubuntu_1](https://user-images.githubusercontent.com/57762932/108174056-f7ebd800-70cc-11eb-9286-326ce9084dbe.png)

![ubuntu_2](https://user-images.githubusercontent.com/57762932/108174071-fc17f580-70cc-11eb-8299-7d8bf2ec11d7.png)

**Comment by susanBuck** [comment] 2021-02-19 16:35
Checking in, @NEOMorpheus33 - Were you able to resolve this issue? Let us know if there's anything else we can do to help.

**Comment by NEOMorpheus33** [comment] 2021-02-19 19:54
Professor  Buck,

I ran the troubleshooting command in the instructions but received another
error message. I did create a private and public hes key. I logged in via
mac OSX with it and via https:// for Github.com commits FYI.

Joseph
Thank You & Sincerely,

B.S Ramapo College Admin
Harvard  Computer Science Certified
Google IT Support Certified
Duke Front End Dev Certified
JF Creative IT Support  <https://www.joepfanning.com>
Mobile: 201 334 8743

**Comment by susanBuck** [comment] 2021-02-22 16:22
What was the error message?

**Comment by NEOMorpheus33** [comment] 2021-02-22 18:40
Susan,

Sorry for the confusion. I use a PC Windows 10 for forum questions.

For the second issue/question I'm using OSX 10.10.0 Macbook Air Yosemite. I
see the issue with the OSX terminal, it looks like I need to reinstall Git.

My actual problem that I'm having now with OSX is getting Apache on Xampp
working. MYSQL server is running through Xampp but not Apache (doesn't go
green). I'll get the error logs to you.

Thank You & Sincerely,

B.S Ramapo College Admin
Harvard  Computer Science Certified
Google IT Support Certified
Duke Front End Dev Certified
JF Creative IT Support  <https://www.joepfanning.com>
Mobile: 201 334 8743

**Comment by karnaout** [comment] 2021-02-22 19:24
If you can share some screenshots @NEOMorpheus33 I might be able to chime in. For the potential Git issue, I did encounter something similar after updating my OSX that one time and I had to run `xcode-select --install` to fix it. Give it a try and see if it solves your Git issue at least.

**Comment by susanBuck** [comment] 2021-02-26 15:24
@NEOMorpheus33 And I have been communicating about this problem off-forum via email, so I'm going to go ahead and close this thread.

**Closed as completed by susanBuck** 2021-02-26 15:24 UTC
